/* Generated by the protocol buffer compiler.  DO NOT EDIT! */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C_NO_DEPRECATED
#define PROTOBUF_C_NO_DEPRECATED
#endif

#include "test_inner_product.pb-c.h"
void   inner_product__msg__init
                     (InnerProduct__Msg         *message)
{
  static InnerProduct__Msg init_value = INNER_PRODUCT__MSG__INIT;
  *message = init_value;
}
size_t inner_product__msg__get_packed_size
                     (const InnerProduct__Msg *message)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &inner_product__msg__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t inner_product__msg__pack
                     (const InnerProduct__Msg *message,
                      uint8_t       *out)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &inner_product__msg__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t inner_product__msg__pack_to_buffer
                     (const InnerProduct__Msg *message,
                      ProtobufCBuffer *buffer)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &inner_product__msg__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
InnerProduct__Msg *
       inner_product__msg__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (InnerProduct__Msg *)
     protobuf_c_message_unpack (&inner_product__msg__descriptor,
                                allocator, len, data);
}
void   inner_product__msg__free_unpacked
                     (InnerProduct__Msg *message,
                      ProtobufCAllocator *allocator)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &inner_product__msg__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor inner_product__msg__field_descriptors[2] =
{
  {
    "vector",
    1,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_INT32,
    PROTOBUF_C_OFFSETOF(InnerProduct__Msg, n_vector),
    PROTOBUF_C_OFFSETOF(InnerProduct__Msg, vector),
    NULL,
    NULL,
    1,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "value",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(InnerProduct__Msg, value),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned inner_product__msg__field_indices_by_name[] = {
  1,   /* field[1] = value */
  0,   /* field[0] = vector */
};
static const ProtobufCIntRange inner_product__msg__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor inner_product__msg__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "inner_product.msg",
  "Msg",
  "InnerProduct__Msg",
  "inner_product",
  sizeof(InnerProduct__Msg),
  2,
  inner_product__msg__field_descriptors,
  inner_product__msg__field_indices_by_name,
  1,  inner_product__msg__number_ranges,
  (ProtobufCMessageInit) inner_product__msg__init,
  NULL,NULL,NULL    /* reserved[123] */
};
