/* Generated by the protocol buffer compiler.  DO NOT EDIT! */

#ifndef PROTOBUF_C_test_5finner_5fproduct_2eproto__INCLUDED
#define PROTOBUF_C_test_5finner_5fproduct_2eproto__INCLUDED

#include <google/protobuf-c/protobuf-c.h>

PROTOBUF_C_BEGIN_DECLS


typedef struct _InnerProduct__Msg InnerProduct__Msg;


/* --- enums --- */


/* --- messages --- */

struct  _InnerProduct__Msg
{
  ProtobufCMessage base;
  size_t n_vector;
  int32_t *vector;
  int32_t value;
};
#define INNER_PRODUCT__MSG__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&inner_product__msg__descriptor) \
    , 0,NULL, 0 }


/* InnerProduct__Msg methods */
void   inner_product__msg__init
                     (InnerProduct__Msg         *message);
size_t inner_product__msg__get_packed_size
                     (const InnerProduct__Msg   *message);
size_t inner_product__msg__pack
                     (const InnerProduct__Msg   *message,
                      uint8_t             *out);
size_t inner_product__msg__pack_to_buffer
                     (const InnerProduct__Msg   *message,
                      ProtobufCBuffer     *buffer);
InnerProduct__Msg *
       inner_product__msg__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   inner_product__msg__free_unpacked
                     (InnerProduct__Msg *message,
                      ProtobufCAllocator *allocator);
/* --- per-message closures --- */

typedef void (*InnerProduct__Msg_Closure)
                 (const InnerProduct__Msg *message,
                  void *closure_data);

/* --- services --- */


/* --- descriptors --- */

extern const ProtobufCMessageDescriptor inner_product__msg__descriptor;

PROTOBUF_C_END_DECLS


#endif  /* PROTOBUF_test_5finner_5fproduct_2eproto__INCLUDED */
