image: docker:stable
services:
  - docker:dind

variables:
  REGISTRY: gitlab.informatik.hu-berlin.de:4567
  CONTAINER_TEST_IMAGE: $REGISTRY/$CI_PROJECT_PATH:$CI_COMMIT_SHA
  CONTAINER_RELEASE_IMAGE: $REGISTRY/$CI_PROJECT_PATH:latest

before_script:
  - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN $REGISTRY

build:
  stage: build
  script:
    - docker pull $CONTAINER_RELEASE_IMAGE || true
    - docker build --cache-from $CONTAINER_RELEASE_IMAGE,archlinux/base --tag $CONTAINER_TEST_IMAGE .
    - docker push $CONTAINER_TEST_IMAGE
  tags:
    - dockerimage

push:
  stage: deploy
  script:
    - docker pull $CONTAINER_TEST_IMAGE
    - docker tag $CONTAINER_TEST_IMAGE $CONTAINER_RELEASE_IMAGE
    - docker push $CONTAINER_RELEASE_IMAGE
  only:
    - master
